name: 'Automate Terraform Command'

on:
  push:
    branches:
      - 'main'
    paths:
    - '**/*.tf'
    - '*.sh'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: 'us-east-1'

jobs:
  manages:
    runs-on: 'ubuntu:latest'
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Organize fmt'
        run: terraform fmt

      - name: 'Validate'
        run: terraform validate

      - name: 'Planning'
        run: terraform plan